### ISSUE TITLE
Add your first solution to any question

### ISSUE THREAD

**Issue by burninghell2002** [burninghell2002/competitive_solution#3] opened 2020-09-25 11:26 UTC

**Comment by devsingh1234** [comment] 2020-09-25 11:32
I WILL LIKE TO DO THIS WORK I AM A TOTAL BIGNNER

**Comment by abhinitrpr** [comment] 2020-09-25 11:33
I would like to do this

**Comment by chehak123** [comment] 2020-09-25 11:44
I would like to work on this

**Comment by burninghell2002** [comment] 2020-09-25 12:08
Okay go ahead!!

**Comment by dikshantmali** [comment] 2020-09-25 12:38
I also want to work on this issue
please assign it to me as well. and please tell me in which directory should  I add my solution like Leetcode/dikshant is fine

**Comment by dikshantmali** [comment] 2020-09-25 12:41
Can I use c++ language? to add solution

**Comment by dikshantmali** [comment] 2020-09-25 13:15
I have made a pull request, please verify and merge it

**Comment by RiyaGoel27** [comment] 2020-09-25 16:32
Hi , I would also like to work on this

**Comment by RiyaGoel27** [comment] 2020-09-25 16:39
Can I also work on this?

**Comment by Riyagoel2** [comment] 2020-09-25 17:40
Hi , I am sorry I used the wrong id . Can you please reassign me  . I'll delete the previous comment

**Comment by codeshruti** [comment] 2020-09-25 17:43
I want to work on this issue. Please assign this to me.

**Comment by burninghell2002** [comment] 2020-09-26 04:36
@dikshantmali yes you can do that

**Comment by Manoj13-coder** [comment] 2020-09-28 18:14
May i add more competitive questions ?

**Comment by JINDAL-JJ** [comment] 2020-09-29 16:24
I would also like to add some of my codechef solutions in cpp.

**Comment by Sindhu-321** [comment] 2020-10-23 15:41
If the issue is still open may i give it a try? I would like to add some c++ solutions to some codeforces problems. Thanks!

**Closed** 2021-09-30 18:13 UTC
Labels: good first issue, hacktoberfest
